'''Faça um programa que leia algo pelo teclado e mostre na tela o seu tipo primitivo e todas as informações possíveis sobre ele.'''
a = input("digite algo: ")
print("o tipo primitivo é ", type(a))
print("só tem espaços?", a.isspace())
print("é um numero?", a.isnumeric())
print("é alfabetico?", a.isalpha())
print("é alfanúmerico?", a.isalnum())
print("esta em maisculo?", a.isupper())
print("esta em minusculo?", a.islower())
print("esta capitalizado?", a.istitle())
